check_singularity_sif_support: don't leave detritus behind
more important in the job wrapper than the node check but it's easier to make the functions the same.

diff --git a/node-check/itb-osgvo-default-image b/node-check/itb-osgvo-default-image
--- a/node-check/itb-osgvo-default-image
+++ b/node-check/itb-osgvo-default-image
@@ -100,15 +100,26 @@ function check_singularity_sif_support {
     local sylabs_alpine="library://alpine:3"
 
     (
-        singularity build --force alpine.sif "$cvmfs_alpine" ||
-            singularity pull --force alpine.sif "$osghub_alpine" ||
-            singularity pull --force alpine.sif "$sylabs_alpine" ||
-            { echo "*** Could not create alpine.sif"; exit 1; }
-    ) &> alpine.sif.log  || return $?
+        singularity build --force .gwms-alpine.sif "$cvmfs_alpine" ||
+            singularity pull --force .gwms-alpine.sif "$osghub_alpine" ||
+            singularity pull --force .gwms-alpine.sif "$sylabs_alpine" ||
+            echo "All sources failed - could not create .gwms-alpine.sif"
+    ) &> .gwms-alpine.sif.log; ret=$?
+    if [[ $ret != 0 ]]; then
+        info "check_singularity_sif_support() failed to download alpine image"
+        cat .gwms-alpine.sif.log
+        rm -f .gwms-alpine.sif.log .gwms-alpine.sif
+        return $ret
+    fi
+    rm -f .gwms-alpine.sif.log
 
-    output=$(singularity run alpine.sif /bin/true 2>&1) || return $?
+    output=$(singularity run .gwms-alpine.sif /bin/true 2>&1)
+    ret=$?
+    rm -f .gwms-alpine.sif
 
-    if grep -q "temporary sandbox" <<< "$output"; then
+    if [[ $ret != 0 ]]; then
+        return $ret
+    elif grep -q "temporary sandbox" <<< "$output"; then
         return 1
     else
         return 0
