Updated stash test for ITB

diff --git a/node-check/itb-osgvo-additional-htcondor-config b/node-check/itb-osgvo-additional-htcondor-config
--- a/node-check/itb-osgvo-additional-htcondor-config
+++ b/node-check/itb-osgvo-additional-htcondor-config
@@ -137,12 +137,19 @@ add_condor_vars_line CHIRP_DELAYED_UPDATE_PREFIX "C" "-" "+" "N" "N" "-"
 ###########################################################
 # stashcp 
 STASHCP=$PWD/client/stashcp
+STASHCP_DEBUG="-d"
+STASHCP_TEST_FILE="/osgconnect/public/dweitzel/stashcp/test.file"
 STASH_PLUGIN=$PWD/client/stash_plugin
 chmod 755 $STASHCP $STASH_PLUGIN
 
 TIMEOUT=$(which timeout 2>/dev/null)
 if [ "x$TIMEOUT" != "x" ]; then
-    TIMEOUT="$TIMEOUT 10s"
+    TIMEOUT="$TIMEOUT 120s"
+fi
+
+TIME=$(which time 2>/dev/null)
+if [ "x$TIME" != "x" ]; then
+    TIME="$TIME -qo stashcp-test.time -f %e"
 fi
 
 glidein_site=`grep -i "^GLIDEIN_Site " $glidein_config | awk '{print $2}'`
@@ -151,11 +158,27 @@ if [[ -z $OSG_SITE_NAME ]]; then
 fi
 
 # also run a simple test
-if ($TIMEOUT $STASHCP /osgconnect/public/dweitzel/stashcp/test.file stashcp-test.file) &>/dev/null &&
-   [[ $OSG_SITE_NAME != "UTC-Epyc" ]]; then
+info "Testing $STASHCP $STASHCP_DEBUG $STASHCP_TEST_FILE..."
+if $TIME $TIMEOUT $STASHCP $STASHCP_DEBUG $STASHCP_TEST_FILE stashcp-test.file >> stashcp-test.log 2>&1; then
+    if [ -f stashcp-test.time ]; then
+        info "Succeeded (in $(head -1 stashcp-test.time)s)!"
+    else
+        info "Succeeded!"
+    fi
     add_config_line FILETRANSFER_PLUGINS "\$(FILETRANSFER_PLUGINS),$STASH_PLUGIN"
     add_condor_vars_line FILETRANSFER_PLUGINS "C" "-" "+" "N" "N" "-"
+else
+    if [ "$?" -eq "124" ]; then
+        warn "Failed (timed out after 120s)! stashcp output:"
+    elif [ -f stashcp-test.time ]; then
+        warn "Failed (in $(cat stashcp-test.time)s)! stashcp output:"
+    else
+        warn "Failed! stashcp output:"
+    fi
+    while read line; do warn "$line"; done < stashcp-test.log
 fi
+
+###########################################################
 
 echo "All done (osgvo-additional-htcondor-config)"
 
