Verify http_proxy and set HasFileTransferPluginMethods accordingly

diff --git a/node-check/osgvo-advertise-base b/node-check/osgvo-advertise-base
--- a/node-check/osgvo-advertise-base
+++ b/node-check/osgvo-advertise-base
@@ -31,7 +31,7 @@
 # OSG_GLIDEIN_VERSION is an ever-increasing version of the glideins.
 # This can be used by negotiators or users, for example to match
 # against a glidein newer than some base with new features.
-OSG_GLIDEIN_VERSION=553
+OSG_GLIDEIN_VERSION=554
 #######################################################################
 
 
@@ -189,6 +189,38 @@ if [ "x$VER" != "x" ]; then
     if [ $VER -gt 10000 ]; then
         advertise OSG_HOST_KERNEL_VERSION "$VER" "I"
     fi
+fi
+
+# verify http_proxy/OSG_SQUID_LOCATION
+PROXY_CHECKS=0
+PROXY_LOCATION=""
+if [ -e $TEST_FILE_4H.http_proxy ]; then
+    PROXY_CHECKS=$(cat $TEST_FILE_4H.http_proxy.checks)
+    PROXY_LOCATION=$(cat $TEST_FILE_4H.http_proxy.location)
+else
+    CURL=$(curlio --version 2>/dev/null)
+    for PROXY_CANDIDATE in $http_proxy $OSG_SQUID_LOCATION; do
+        PROXY_CHECKS=$(($PROXY_CHECKS + 1))
+        if [ "x$CURL" != "x" ]; then
+            env http_proxy=$PROXY_CANDIDATE curl -s -m 10 -o /dev/null http://flock.opensciencegrid.org/proxy-test.html
+        else
+            env http_proxy=$PROXY_CANDIDATE wget -q --timeout 10 -O /dev/null http://flock.opensciencegrid.org/proxy-test.html
+        fi
+        if [ $? = 0 ]; then
+            PROXY_LOCATION="$PROXY_CANDIDATE"
+            break
+        fi
+    done
+    echo $PROXY_CHECKS >$TEST_FILE_4H.http_proxy.checks
+    echo $PROXY_LOCATION >$TEST_FILE_4H.http_proxy.location
+fi
+
+if [ "x$PROXY_LOCATION" = "x" -a $PROXY_CHECKS -gt 0 ]; then
+    # checks peformed, but failed - limit what file transfers we can do
+    advertise HasFileTransferPluginMethods "data,ftp,file" "S"
+fi
+if [ "x$PROXY_LOCATION" != "x" ]; then
+    advertise "http_proxy" "$PROXY_LOCATION" "S"
 fi
 
 # some images require unsquashfs
