Removed x509 auth for OSPool. Carried stashcp and disk hold code from ITB to production.

diff --git a/node-check/osgvo-additional-htcondor-config b/node-check/osgvo-additional-htcondor-config
--- a/node-check/osgvo-additional-htcondor-config
+++ b/node-check/osgvo-additional-htcondor-config
@@ -1,6 +1,15 @@
-#!/bin/bash                                                                                                         
-                                                                                                                    
-glidein_config="$1"                                                                                                 
+#!/bin/bash
+
+glidein_config="$1"
+
+function info {
+    echo "INFO  " $@ 1>&2
+}
+
+function warn {
+    echo "WARN  " $@ 1>&2
+}
+
 
 ###########################################################
 # import add_config_line and add_condor_vars_line functions
@@ -78,6 +87,43 @@ if [[ $allocated_cpus -gt 0 && $total_cpus -gt 0 ]]; then
     fi
 fi
 
+set_unexported_condor_config_attribute () {
+    # Sets the value of a config knob in the condor config;
+    # does not export it as a startd attribute, nor does it export it to the job environment
+    # Reference: https://glideinwms.fnal.gov/doc.prd/factory/custom_vars.html
+    local name value
+    name=$1
+    value=$2
+    add_config_line "$name" "$value"
+    add_condor_vars_line "$name" \
+        "C" `# unquoted string (i.e. HTCondor keyword or expression)` \
+        "-" `# no default value` \
+        "+" `# also use $name for the name of the config knob` \
+        "N" `# a value is not required for this attribute` \
+        "N" `# do not have the startd publish this to the collector` \
+        "-" `# do not export to the user job environment`
+}
+
+# Hold jobs if they exceed allocated disk (OSPOOL-26)
+
+# Helper macros
+set_unexported_condor_config_attribute  disk_exceeded  '(JobUniverse != 13 && DiskUsage =!= UNDEFINED && DiskUsage > Disk)'
+set_unexported_condor_config_attribute  hold_reason_disk_exceeded  'disk usage exceeded request_disk'
+
+# Actual knobs. The following is the equivalent of
+# use POLICY : WANT_HOLD_IF(disk_exceeded, $(HOLD_SUBCODE_disk_exceeded:104), $(hold_reason_disk_exceeded))
+# since metaknobs are not supported.
+set_unexported_condor_config_attribute  PREEMPT  '$(disk_exceeded) || $(PREEMPT:false)'
+set_unexported_condor_config_attribute  MAXJOBRETIREMENTTIME  'ifthenelse($(disk_exceeded),-1,$(MAXJOBRETIREMENTTIME:0))'
+
+set_unexported_condor_config_attribute  WANT_SUSPEND  '$(disk_exceeded) =!= true && $(WANT_SUSPEND:false)'
+
+set_unexported_condor_config_attribute  WANT_HOLD  '(JobUniverse != 1 && $(disk_exceeded)) || $(WANT_HOLD:false)'
+set_unexported_condor_config_attribute  WANT_HOLD_SUBCODE  'ifThenElse($(disk_exceeded), 104 , $(WANT_HOLD_SUBCODE:UNDEFINED))'
+set_unexported_condor_config_attribute  WANT_HOLD_REASON  'ifThenElse($(disk_exceeded), "$(hold_reason_disk_exceeded)", $(WANT_HOLD_REASON:UNDEFINED))'
+
+# End OSPOOL-26
+
 ###########################################################
 # potential fix for SU NAT issues
 add_config_line CCB_HEARTBEAT_INTERVAL "120"
@@ -100,12 +146,26 @@ add_condor_vars_line CHIRP_DELAYED_UPDATE_PREFIX "C" "-" "+" "N" "N" "-"
 ###########################################################
 # stashcp 
 STASHCP=$PWD/client/stashcp
+STASHCP_DEBUG="-d"
+STASHCP_TEST_FILE="/osgconnect/public/dweitzel/stashcp/test.file"
 STASH_PLUGIN=$PWD/client/stash_plugin
 chmod 755 $STASHCP $STASH_PLUGIN
 
 TIMEOUT=$(which timeout 2>/dev/null)
 if [ "x$TIMEOUT" != "x" ]; then
-    TIMEOUT="$TIMEOUT 10s"
+    TIMEOUT="$TIMEOUT 120s"
+fi
+
+# The bash builtin time is no good because it pollutes
+# stderr with hardcoded real, sys, and user lines.
+TIME=$(which time 2>/dev/null)
+if [ "x$TIME" != "x" ]; then
+    # Without --quiet, newer versions of TIME(1)
+    # will prepend an extra line to the output
+    # if the process exits with a non-zero exit code.
+    # Therefore, we use $(tail -1 stashcp-test.time)
+    # below to get the runtime of stashcp.
+    TIME="$TIME --output=stashcp-test.time --format=%e"
 fi
 
 glidein_site=`grep -i "^GLIDEIN_Site " $glidein_config | awk '{print $2}'`
@@ -113,12 +173,28 @@ if [[ -z $OSG_SITE_NAME ]]; then
     OSG_SITE_NAME=$glidein_site
 fi
 
-# also run a simple test
-if ($TIMEOUT $STASHCP /osgconnect/public/dweitzel/stashcp/test.file stashcp-test.file) &>/dev/null &&
-   [[ $OSG_SITE_NAME != "UTC-Epyc" ]]; then
+# also run a simple test (TODO: make this IGWN-specific)
+info "Testing $STASHCP $STASHCP_DEBUG $STASHCP_TEST_FILE..."
+if $TIME $TIMEOUT $STASHCP $STASHCP_DEBUG $STASHCP_TEST_FILE stashcp-test.file >> stashcp-test.log 2>&1; then
+    if [ -f stashcp-test.time ]; then
+        info "Succeeded (in $(tail -1 stashcp-test.time)s)!"
+    else
+        info "Succeeded!"
+    fi
     add_config_line FILETRANSFER_PLUGINS "\$(FILETRANSFER_PLUGINS),$STASH_PLUGIN"
     add_condor_vars_line FILETRANSFER_PLUGINS "C" "-" "+" "N" "N" "-"
+else
+    if [ "$?" -eq "124" ]; then
+        warn "Failed (timed out after 120s)! stashcp output:"
+    elif [ -f stashcp-test.time ]; then
+        warn "Failed (in $(tail -1 stashcp-test.time)s)! stashcp output:"
+    else
+        warn "Failed! stashcp output:"
+    fi
+    while read line; do warn "$line"; done < stashcp-test.log
 fi
+
+###########################################################
 
 echo "All done (osgvo-additional-htcondor-config)"
 
