Moved from Singularity containall to contain/ipc/pid

diff --git a/node-check/osgvo-node-advertise b/node-check/osgvo-node-advertise
--- a/node-check/osgvo-node-advertise
+++ b/node-check/osgvo-node-advertise
@@ -222,19 +222,38 @@ if [ "x$OSG_SINGULARITY_REEXEC" = "x" ]; then
     # in the execing, like:
     # ERROR  : Could not identify basedir for home directory path: /
     if [ "x$HAS_SINGULARITY" = "xTrue" ]; then
-        info "$OSG_SINGULARITY_PATH exec --home $PWD:/srv --bind /cvmfs --pwd /srv --scratch /var/tmp --scratch /tmp --containall $OSG_SINGULARITY_IMAGE_DEFAULT echo Hello World | grep Hello World"
+        info "$OSG_SINGULARITY_PATH exec --home $PWD:/srv --bind /cvmfs --pwd /srv --scratch /var/tmp --scratch /tmp --contain --ipc --pid $OSG_SINGULARITY_IMAGE_DEFAULT echo Hello World | grep Hello World"
         if ! ($OSG_SINGULARITY_PATH exec --home $PWD:/srv \
                                          --bind /cvmfs \
                                          --pwd /srv \
                                          --scratch /var/tmp \
                                          --scratch /tmp \
-                                         --containall \
+                                         --contain --ipc --pid \
                                          "$OSG_SINGULARITY_IMAGE_DEFAULT" \
                                          echo "Hello World" \
                                          | grep "Hello World") 1>&2 \
         ; then
             # singularity simple exec failed - we are done
             info "Simple singularity exec inside $OSG_SINGULARITY_IMAGE_DEFAULT failed."
+            HAS_SINGULARITY="False"
+        fi
+    fi
+    
+    # also verify that the env is inherited correctly
+    if [ "x$HAS_SINGULARITY" = "xTrue" ]; then
+        info "$OSG_SINGULARITY_PATH exec --home $PWD:/srv --bind /cvmfs --pwd /srv --scratch /var/tmp --scratch /tmp --contain --ipc --pid $OSG_SINGULARITY_IMAGE_DEFAULT env | grep OSG_SINGULARITY_IMAGE_DEFAULT"
+        if ! ($OSG_SINGULARITY_PATH exec --home $PWD:/srv \
+                                         --bind /cvmfs \
+                                         --pwd /srv \
+                                         --scratch /var/tmp \
+                                         --scratch /tmp \
+                                         --contain --ipc --pid \
+                                         "$OSG_SINGULARITY_IMAGE_DEFAULT" \
+                                         env \
+                                         | grep OSG_SINGULARITY_IMAGE_DEFAULT) 1>&2 \
+        ; then
+            # singularity env fail - we are done
+            warn "Singularity is not inheriting the outside environment"
             HAS_SINGULARITY="False"
         fi
     fi
@@ -263,13 +282,13 @@ if [ "x$OSG_SINGULARITY_REEXEC" = "x" ]; then
 
         # let "inside" script know we are re-execing
         export OSG_SINGULARITY_REEXEC=1
-        info "$OSG_SINGULARITY_PATH exec --home $SING_OUTSIDE_BASE_DIR:/srv --bind /cvmfs --pwd /srv --scratch /var/tmp --scratch /tmp --containall $OSG_SINGULARITY_IMAGE_DEFAULT $CMD"
+        info "$OSG_SINGULARITY_PATH exec --home $SING_OUTSIDE_BASE_DIR:/srv --bind /cvmfs --pwd /srv --scratch /var/tmp --scratch /tmp --contain --ipc --pid $OSG_SINGULARITY_IMAGE_DEFAULT $CMD"
         if $OSG_SINGULARITY_PATH exec --home $SING_OUTSIDE_BASE_DIR:/srv \
                                       --bind /cvmfs \
                                       --pwd /srv \
                                       --scratch /var/tmp \
                                       --scratch /tmp \
-                                      --containall \
+                                      --contain --ipc --pid \
                                       "$OSG_SINGULARITY_IMAGE_DEFAULT" \
                                       $CMD \
         ; then
