Added another singularity test to make sure the re-exec of the ad script will work

diff --git a/node-check/osgvo-node-advertise b/node-check/osgvo-node-advertise
--- a/node-check/osgvo-node-advertise
+++ b/node-check/osgvo-node-advertise
@@ -181,7 +181,28 @@ if [ "x$OSG_SINGULARITY_REEXEC" = "x" ]; then
         HAS_SINGULARITY="False"
     fi
 
-    # if we have singularity, we should re-exec this script within the default
+    # Let's do a simple singularity test by echoing something inside, and then
+    # grepping for it outside. This takes care of some errors which happen "late"
+    # in the execing, like:
+    # ERROR  : Could not identify basedir for home directory path: /
+    if [ "x$HAS_SINGULARITY" = "xTrue" ]; then
+        info "$OSG_SINGULARITY_PATH exec --bind /cvmfs --bind $PWD:/srv --pwd /srv --scratch /var/tmp --scratch /tmp --containall $OSG_SINGULARITY_IMAGE_DEFAULT echo Hello World | grep Hello World"
+        if ! ($OSG_SINGULARITY_PATH exec --bind /cvmfs \
+                                         --bind $PWD:/srv \
+                                         --pwd /srv \
+                                         --scratch /var/tmp \
+                                         --scratch /tmp \
+                                         --containall \
+                                         "$OSG_SINGULARITY_IMAGE_DEFAULT" \
+                                         echo "Hello World" \
+                                         | grep "Hello World") 1>&2 \
+        ; then
+            # singularity simple exec failed - we are done
+            HAS_SINGULARITY="False"
+        fi
+    fi
+
+    # If we still think we have singularity, we should re-exec this script within the default
     # container so that we can advertise that environment
     if [ "x$HAS_SINGULARITY" = "xTrue" ]; then
         # We want to map the full glidein dir to /srv inside the container. This is so 
